name:                idiomaticca
version:             0.1.0.0
github:              "metasepi/idiomaticca"
license:             AGPL-3
author:              "Kiwamu Okabe"
maintainer:          "kiwamu@debian.or.jp"
copyright:           "2019 Metasepi team"

extra-source-files:
- README.md

synopsis:            An utility to translate IDIOMATIC C code into ATS
category:            Language

description:         Please see the README on GitHub at <https://github.com/metasepi/idiomaticca#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- language-ats
- language-c
- optparse-applicative

library:
  source-dirs: src

executables:
  idiomaticca:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idiomaticca

tests:
  idiomaticca-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idiomaticca
